[2022-02-01 17:26:02,186] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.first_csv manual__2022-02-01T17:26:00.903366+00:00 [queued]>
[2022-02-01 17:26:02,198] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.first_csv manual__2022-02-01T17:26:00.903366+00:00 [queued]>
[2022-02-01 17:26:02,198] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 17:26:02,198] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 17:26:02,198] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 17:26:02,212] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): first_csv> on 2022-02-01 17:26:00.903366+00:00
[2022-02-01 17:26:02,218] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2022-02-01 17:26:02,223] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'first_csv', 'manual__2022-02-01T17:26:00.903366+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpaq07vh_9', '--error-file', '/tmp/tmp5crxow0p']
[2022-02-01 17:26:02,224] {standard_task_runner.py:77} INFO - Job 29: Subtask first_csv
[2022-02-01 17:26:02,293] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.first_csv manual__2022-02-01T17:26:00.903366+00:00 [running]> on host 1f177efe7f75
[2022-02-01 17:26:02,362] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=first_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T17:26:00.903366+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-01T17:26:00.903366+00:00
[2022-02-01 17:26:02,365] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 13, in _clean_drugs
    df_drugs = pd.read_csv("drugs.csv", header=0, index_col=None, sep=',', encoding="utf-8")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'drugs.csv'
[2022-02-01 17:26:02,382] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_dag, task_id=first_csv, execution_date=20220201T172600, start_date=20220201T172602, end_date=20220201T172602
[2022-02-01 17:26:02,399] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task first_csv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 13, in _clean_drugs
    df_drugs = pd.read_csv("drugs.csv", header=0, index_col=None, sep=',', encoding="utf-8")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'drugs.csv'
[2022-02-01 17:26:02,435] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-01 17:26:02,487] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
